- id: google_night_vol
  alias: 1. Google Home Night Volume
  trigger:
    platform: time
    at: '22:00:00'
  condition:
    condition: state
    entity_id: media_player.living_room_home
    state: 'off'
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room_home
      data:
        volume_level: .10

- id: google_normal_vol
  alias: 2. Google Home Normal Volume
  trigger:
    platform: time
    at: '16:00:00'
  condition:
    condition: state
    entity_id: media_player.living_room_home
    state: 'off'
  action:
    - service: media_player.volume_set
      entity_id: media_player.living_room_home
      data:
        volume_level: .45

- id: lights_off
  alias: 3. Lights off - morning
  trigger:
    platform: time
    at: '09:00:00'
  condition:
    condition: state
    entity_id: group.people
    state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: group.all_lights
